language: android

before_install:
    - yes | sdkmanager "platforms;android-28"

jdk:
 - oraclejdk8

sudo: required
android:
  components:
    - tools
    - tools
    - platform-tools
    - build-tools-27.0.1
    - android-28
    - android-26
    - android-19
    - extra-android-support
    - extra-android-m2repository
    - extra-google-m2repository
    - sys-img-armeabi-v7a-android-19
  licenses:
    - .+

before_script:
  - echo no | android create avd --force -n test -t android-19 --abi armeabi-v7a
  - emulator -avd test -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell settings put global window_animation_scale 0 &
  - adb shell settings put global transition_animation_scale 0 &
  - adb shell settings put global animator_duration_scale 0 &
  - adb shell input keyevent 82 &

notifications:
  email: false
