name: Conflict Test

on:
  push:
    branches: [ master, beta ]
  pull_request:
    types: [synchronize]
    branches: [ master, beta ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check if PR contains merge conflict issue
      uses: eps1lon/actions-label-merge-conflict@releases/2.x
      if: env.LABELING_TOKEN != '' && env.LABELING_TOKEN != null
      id: check
      with:
        dirtyLabel: "conflicting"
        repoToken: "${{ secrets.GITHUB_TOKEN  }}"
        continueOnMissingPermissions: true
        commentOnDirty: 'This pull request has conflicting changes, the author must resolve the conflicts before this pull request can be merged.'
        commentOnClean: 'Conflicts have been resolved. A maintainer will take a look shortly.'
      env:
        LABELING_TOKEN: ${{secrets.GITHUB_TOKEN }}

# Credits: https://baywet.github.io/pull-request-conflict-github-workflow/